#!/usr/bin/env python

# Copyright (c) 2007 Forest Bond.
# This file is part of the pytagsfs software package.
#
# pytagsfs is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License version 2 as published by the Free
# Software Foundation.
#
# A copy of the license has been included in the COPYING file.

import sys

if __name__ == '__main__':
    from pytagsfs.pytags import main
    sys.exit(main())
